logging:
  level:
    org.springframework.integration: 'DEBUG'
    org.springframework.integration.handler.LoggingHandler: 'INFO'
    demo: 'INFO'

spring:
  application:
    routing:
      key: demo.key
    inbound:
      queue: demo.inbound.queue
      exchange: demo.inbound.exchange
    outbound:
      queue: demo.outbound.queue
      exchange: demo.outbound.exchange

server:
  port: 9091