logging:
  org.springframework: info
  demo: info

spring:
  application:
    routing:
      key: demo.key
    inbound:
      queue: demo.inbound.queue
      exchange: demo.inbound.exchange
    outbound:
      queue: demo.outbound.queue
      exchange: demo.outbound.exchange